name: Java package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Configure AWS Credentials
      uses: youyo/awscredswrap@master
      with:
        role_arn:  ${{ secrets.AWS_DEV_ROLE_TO_ASSUME }}
        duration_seconds: 1200
        role_session_name: dev
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'eu-central-1'
    - name: Deploy code to Lambda
      run: echo "THIS IS A TEST PACKAGE" > file.txt
      run: zip lambda.zip file.txt
    - uses: yvesgurcan/deploy-lambda-function
      with:
        package: lambda.zip
        function-name: TEST-FUNCTION
